//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomepageApp.ServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetFile(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFile", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetFileAsync(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetItem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItem", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetItemAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLoan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetLoan();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLoan", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetLoanAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItemForConsole", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetItemForConsole();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItemForConsole", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetItemForConsoleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLoanForConsole", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetLoanForConsole();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLoanForConsole", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetLoanForConsoleAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : HomepageApp.ServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<HomepageApp.ServiceReference.WebServiceSoap>, HomepageApp.ServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetFile(string fileName) {
            return base.Channel.GetFile(fileName);
        }
        
        public System.Threading.Tasks.Task<string> GetFileAsync(string fileName) {
            return base.Channel.GetFileAsync(fileName);
        }
        
        public System.Data.DataTable GetItem() {
            return base.Channel.GetItem();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetItemAsync() {
            return base.Channel.GetItemAsync();
        }
        
        public System.Data.DataTable GetLoan() {
            return base.Channel.GetLoan();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetLoanAsync() {
            return base.Channel.GetLoanAsync();
        }
        
        public string GetItemForConsole() {
            return base.Channel.GetItemForConsole();
        }
        
        public System.Threading.Tasks.Task<string> GetItemForConsoleAsync() {
            return base.Channel.GetItemForConsoleAsync();
        }
        
        public string GetLoanForConsole() {
            return base.Channel.GetLoanForConsole();
        }
        
        public System.Threading.Tasks.Task<string> GetLoanForConsoleAsync() {
            return base.Channel.GetLoanForConsoleAsync();
        }
    }
}
