//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomepageApp.WebServiceClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceClient.ERP2_WebServiceSoap")]
    public interface ERP2_WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name args from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmployeeContents", ReplyAction="*")]
        HomepageApp.WebServiceClient.EmployeeContentsResponse EmployeeContents(HomepageApp.WebServiceClient.EmployeeContentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmployeeContents", ReplyAction="*")]
        System.Threading.Tasks.Task<HomepageApp.WebServiceClient.EmployeeContentsResponse> EmployeeContentsAsync(HomepageApp.WebServiceClient.EmployeeContentsRequest request);
        
        // CODEGEN: Generating message contract since element name EmployeeRelativesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmployeeRelatives", ReplyAction="*")]
        HomepageApp.WebServiceClient.EmployeeRelativesResponse EmployeeRelatives(HomepageApp.WebServiceClient.EmployeeRelativesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmployeeRelatives", ReplyAction="*")]
        System.Threading.Tasks.Task<HomepageApp.WebServiceClient.EmployeeRelativesResponse> EmployeeRelativesAsync(HomepageApp.WebServiceClient.EmployeeRelativesRequest request);
        
        // CODEGEN: Generating message contract since element name SickEmployeesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SickEmployees", ReplyAction="*")]
        HomepageApp.WebServiceClient.SickEmployeesResponse SickEmployees(HomepageApp.WebServiceClient.SickEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SickEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<HomepageApp.WebServiceClient.SickEmployeesResponse> SickEmployeesAsync(HomepageApp.WebServiceClient.SickEmployeesRequest request);
        
        // CODEGEN: Generating message contract since element name MostSickEmployeeResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostSickEmployee", ReplyAction="*")]
        HomepageApp.WebServiceClient.MostSickEmployeeResponse MostSickEmployee(HomepageApp.WebServiceClient.MostSickEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostSickEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<HomepageApp.WebServiceClient.MostSickEmployeeResponse> MostSickEmployeeAsync(HomepageApp.WebServiceClient.MostSickEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name args from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllKeys", ReplyAction="*")]
        HomepageApp.WebServiceClient.GetAllKeysResponse GetAllKeys(HomepageApp.WebServiceClient.GetAllKeysRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllKeys", ReplyAction="*")]
        System.Threading.Tasks.Task<HomepageApp.WebServiceClient.GetAllKeysResponse> GetAllKeysAsync(HomepageApp.WebServiceClient.GetAllKeysRequest request);
        
        // CODEGEN: Generating message contract since element name args from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllIndexes", ReplyAction="*")]
        HomepageApp.WebServiceClient.AllIndexesResponse AllIndexes(HomepageApp.WebServiceClient.AllIndexesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllIndexes", ReplyAction="*")]
        System.Threading.Tasks.Task<HomepageApp.WebServiceClient.AllIndexesResponse> AllIndexesAsync(HomepageApp.WebServiceClient.AllIndexesRequest request);
        
        // CODEGEN: Generating message contract since element name args from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllConstraints", ReplyAction="*")]
        HomepageApp.WebServiceClient.AllConstraintsResponse AllConstraints(HomepageApp.WebServiceClient.AllConstraintsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllConstraints", ReplyAction="*")]
        System.Threading.Tasks.Task<HomepageApp.WebServiceClient.AllConstraintsResponse> AllConstraintsAsync(HomepageApp.WebServiceClient.AllConstraintsRequest request);
        
        // CODEGEN: Generating message contract since element name AllTableNames1Result from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllTableNames1", ReplyAction="*")]
        HomepageApp.WebServiceClient.AllTableNames1Response AllTableNames1(HomepageApp.WebServiceClient.AllTableNames1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllTableNames1", ReplyAction="*")]
        System.Threading.Tasks.Task<HomepageApp.WebServiceClient.AllTableNames1Response> AllTableNames1Async(HomepageApp.WebServiceClient.AllTableNames1Request request);
        
        // CODEGEN: Generating message contract since element name AllTableNames2Result from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllTableNames2", ReplyAction="*")]
        HomepageApp.WebServiceClient.AllTableNames2Response AllTableNames2(HomepageApp.WebServiceClient.AllTableNames2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllTableNames2", ReplyAction="*")]
        System.Threading.Tasks.Task<HomepageApp.WebServiceClient.AllTableNames2Response> AllTableNames2Async(HomepageApp.WebServiceClient.AllTableNames2Request request);
        
        // CODEGEN: Generating message contract since element name AllEmployeeColumns1Result from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllEmployeeColumns1", ReplyAction="*")]
        HomepageApp.WebServiceClient.AllEmployeeColumns1Response AllEmployeeColumns1(HomepageApp.WebServiceClient.AllEmployeeColumns1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllEmployeeColumns1", ReplyAction="*")]
        System.Threading.Tasks.Task<HomepageApp.WebServiceClient.AllEmployeeColumns1Response> AllEmployeeColumns1Async(HomepageApp.WebServiceClient.AllEmployeeColumns1Request request);
        
        // CODEGEN: Generating message contract since element name AllEmployeeColumns2Result from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllEmployeeColumns2", ReplyAction="*")]
        HomepageApp.WebServiceClient.AllEmployeeColumns2Response AllEmployeeColumns2(HomepageApp.WebServiceClient.AllEmployeeColumns2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllEmployeeColumns2", ReplyAction="*")]
        System.Threading.Tasks.Task<HomepageApp.WebServiceClient.AllEmployeeColumns2Response> AllEmployeeColumns2Async(HomepageApp.WebServiceClient.AllEmployeeColumns2Request request);
        
        // CODEGEN: Generating message contract since element name EmployeeTablesTableNamesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmployeeTablesTableNames", ReplyAction="*")]
        HomepageApp.WebServiceClient.EmployeeTablesTableNamesResponse EmployeeTablesTableNames(HomepageApp.WebServiceClient.EmployeeTablesTableNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmployeeTablesTableNames", ReplyAction="*")]
        System.Threading.Tasks.Task<HomepageApp.WebServiceClient.EmployeeTablesTableNamesResponse> EmployeeTablesTableNamesAsync(HomepageApp.WebServiceClient.EmployeeTablesTableNamesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmployeeContentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmployeeContents", Namespace="http://tempuri.org/", Order=0)]
        public HomepageApp.WebServiceClient.EmployeeContentsRequestBody Body;
        
        public EmployeeContentsRequest() {
        }
        
        public EmployeeContentsRequest(HomepageApp.WebServiceClient.EmployeeContentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmployeeContentsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string args;
        
        public EmployeeContentsRequestBody() {
        }
        
        public EmployeeContentsRequestBody(string args) {
            this.args = args;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmployeeContentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmployeeContentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public HomepageApp.WebServiceClient.EmployeeContentsResponseBody Body;
        
        public EmployeeContentsResponse() {
        }
        
        public EmployeeContentsResponse(HomepageApp.WebServiceClient.EmployeeContentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmployeeContentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HomepageApp.WebServiceClient.ArrayOfString[] EmployeeContentsResult;
        
        public EmployeeContentsResponseBody() {
        }
        
        public EmployeeContentsResponseBody(HomepageApp.WebServiceClient.ArrayOfString[] EmployeeContentsResult) {
            this.EmployeeContentsResult = EmployeeContentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmployeeRelativesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmployeeRelatives", Namespace="http://tempuri.org/", Order=0)]
        public HomepageApp.WebServiceClient.EmployeeRelativesRequestBody Body;
        
        public EmployeeRelativesRequest() {
        }
        
        public EmployeeRelativesRequest(HomepageApp.WebServiceClient.EmployeeRelativesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EmployeeRelativesRequestBody {
        
        public EmployeeRelativesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmployeeRelativesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmployeeRelativesResponse", Namespace="http://tempuri.org/", Order=0)]
        public HomepageApp.WebServiceClient.EmployeeRelativesResponseBody Body;
        
        public EmployeeRelativesResponse() {
        }
        
        public EmployeeRelativesResponse(HomepageApp.WebServiceClient.EmployeeRelativesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmployeeRelativesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HomepageApp.WebServiceClient.ArrayOfString[] EmployeeRelativesResult;
        
        public EmployeeRelativesResponseBody() {
        }
        
        public EmployeeRelativesResponseBody(HomepageApp.WebServiceClient.ArrayOfString[] EmployeeRelativesResult) {
            this.EmployeeRelativesResult = EmployeeRelativesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SickEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SickEmployees", Namespace="http://tempuri.org/", Order=0)]
        public HomepageApp.WebServiceClient.SickEmployeesRequestBody Body;
        
        public SickEmployeesRequest() {
        }
        
        public SickEmployeesRequest(HomepageApp.WebServiceClient.SickEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SickEmployeesRequestBody {
        
        public SickEmployeesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SickEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SickEmployeesResponse", Namespace="http://tempuri.org/", Order=0)]
        public HomepageApp.WebServiceClient.SickEmployeesResponseBody Body;
        
        public SickEmployeesResponse() {
        }
        
        public SickEmployeesResponse(HomepageApp.WebServiceClient.SickEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SickEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HomepageApp.WebServiceClient.ArrayOfString[] SickEmployeesResult;
        
        public SickEmployeesResponseBody() {
        }
        
        public SickEmployeesResponseBody(HomepageApp.WebServiceClient.ArrayOfString[] SickEmployeesResult) {
            this.SickEmployeesResult = SickEmployeesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostSickEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostSickEmployee", Namespace="http://tempuri.org/", Order=0)]
        public HomepageApp.WebServiceClient.MostSickEmployeeRequestBody Body;
        
        public MostSickEmployeeRequest() {
        }
        
        public MostSickEmployeeRequest(HomepageApp.WebServiceClient.MostSickEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MostSickEmployeeRequestBody {
        
        public MostSickEmployeeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostSickEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostSickEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public HomepageApp.WebServiceClient.MostSickEmployeeResponseBody Body;
        
        public MostSickEmployeeResponse() {
        }
        
        public MostSickEmployeeResponse(HomepageApp.WebServiceClient.MostSickEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostSickEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HomepageApp.WebServiceClient.ArrayOfString[] MostSickEmployeeResult;
        
        public MostSickEmployeeResponseBody() {
        }
        
        public MostSickEmployeeResponseBody(HomepageApp.WebServiceClient.ArrayOfString[] MostSickEmployeeResult) {
            this.MostSickEmployeeResult = MostSickEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllKeysRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllKeys", Namespace="http://tempuri.org/", Order=0)]
        public HomepageApp.WebServiceClient.GetAllKeysRequestBody Body;
        
        public GetAllKeysRequest() {
        }
        
        public GetAllKeysRequest(HomepageApp.WebServiceClient.GetAllKeysRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllKeysRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string args;
        
        public GetAllKeysRequestBody() {
        }
        
        public GetAllKeysRequestBody(string args) {
            this.args = args;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllKeysResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllKeysResponse", Namespace="http://tempuri.org/", Order=0)]
        public HomepageApp.WebServiceClient.GetAllKeysResponseBody Body;
        
        public GetAllKeysResponse() {
        }
        
        public GetAllKeysResponse(HomepageApp.WebServiceClient.GetAllKeysResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllKeysResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HomepageApp.WebServiceClient.ArrayOfString[] GetAllKeysResult;
        
        public GetAllKeysResponseBody() {
        }
        
        public GetAllKeysResponseBody(HomepageApp.WebServiceClient.ArrayOfString[] GetAllKeysResult) {
            this.GetAllKeysResult = GetAllKeysResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllIndexesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllIndexes", Namespace="http://tempuri.org/", Order=0)]
        public HomepageApp.WebServiceClient.AllIndexesRequestBody Body;
        
        public AllIndexesRequest() {
        }
        
        public AllIndexesRequest(HomepageApp.WebServiceClient.AllIndexesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllIndexesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string args;
        
        public AllIndexesRequestBody() {
        }
        
        public AllIndexesRequestBody(string args) {
            this.args = args;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllIndexesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllIndexesResponse", Namespace="http://tempuri.org/", Order=0)]
        public HomepageApp.WebServiceClient.AllIndexesResponseBody Body;
        
        public AllIndexesResponse() {
        }
        
        public AllIndexesResponse(HomepageApp.WebServiceClient.AllIndexesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllIndexesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HomepageApp.WebServiceClient.ArrayOfString[] AllIndexesResult;
        
        public AllIndexesResponseBody() {
        }
        
        public AllIndexesResponseBody(HomepageApp.WebServiceClient.ArrayOfString[] AllIndexesResult) {
            this.AllIndexesResult = AllIndexesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllConstraintsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllConstraints", Namespace="http://tempuri.org/", Order=0)]
        public HomepageApp.WebServiceClient.AllConstraintsRequestBody Body;
        
        public AllConstraintsRequest() {
        }
        
        public AllConstraintsRequest(HomepageApp.WebServiceClient.AllConstraintsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllConstraintsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string args;
        
        public AllConstraintsRequestBody() {
        }
        
        public AllConstraintsRequestBody(string args) {
            this.args = args;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllConstraintsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllConstraintsResponse", Namespace="http://tempuri.org/", Order=0)]
        public HomepageApp.WebServiceClient.AllConstraintsResponseBody Body;
        
        public AllConstraintsResponse() {
        }
        
        public AllConstraintsResponse(HomepageApp.WebServiceClient.AllConstraintsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllConstraintsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HomepageApp.WebServiceClient.ArrayOfString[] AllConstraintsResult;
        
        public AllConstraintsResponseBody() {
        }
        
        public AllConstraintsResponseBody(HomepageApp.WebServiceClient.ArrayOfString[] AllConstraintsResult) {
            this.AllConstraintsResult = AllConstraintsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllTableNames1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllTableNames1", Namespace="http://tempuri.org/", Order=0)]
        public HomepageApp.WebServiceClient.AllTableNames1RequestBody Body;
        
        public AllTableNames1Request() {
        }
        
        public AllTableNames1Request(HomepageApp.WebServiceClient.AllTableNames1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AllTableNames1RequestBody {
        
        public AllTableNames1RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllTableNames1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllTableNames1Response", Namespace="http://tempuri.org/", Order=0)]
        public HomepageApp.WebServiceClient.AllTableNames1ResponseBody Body;
        
        public AllTableNames1Response() {
        }
        
        public AllTableNames1Response(HomepageApp.WebServiceClient.AllTableNames1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllTableNames1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HomepageApp.WebServiceClient.ArrayOfString[] AllTableNames1Result;
        
        public AllTableNames1ResponseBody() {
        }
        
        public AllTableNames1ResponseBody(HomepageApp.WebServiceClient.ArrayOfString[] AllTableNames1Result) {
            this.AllTableNames1Result = AllTableNames1Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllTableNames2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllTableNames2", Namespace="http://tempuri.org/", Order=0)]
        public HomepageApp.WebServiceClient.AllTableNames2RequestBody Body;
        
        public AllTableNames2Request() {
        }
        
        public AllTableNames2Request(HomepageApp.WebServiceClient.AllTableNames2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AllTableNames2RequestBody {
        
        public AllTableNames2RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllTableNames2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllTableNames2Response", Namespace="http://tempuri.org/", Order=0)]
        public HomepageApp.WebServiceClient.AllTableNames2ResponseBody Body;
        
        public AllTableNames2Response() {
        }
        
        public AllTableNames2Response(HomepageApp.WebServiceClient.AllTableNames2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllTableNames2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HomepageApp.WebServiceClient.ArrayOfString[] AllTableNames2Result;
        
        public AllTableNames2ResponseBody() {
        }
        
        public AllTableNames2ResponseBody(HomepageApp.WebServiceClient.ArrayOfString[] AllTableNames2Result) {
            this.AllTableNames2Result = AllTableNames2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllEmployeeColumns1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllEmployeeColumns1", Namespace="http://tempuri.org/", Order=0)]
        public HomepageApp.WebServiceClient.AllEmployeeColumns1RequestBody Body;
        
        public AllEmployeeColumns1Request() {
        }
        
        public AllEmployeeColumns1Request(HomepageApp.WebServiceClient.AllEmployeeColumns1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AllEmployeeColumns1RequestBody {
        
        public AllEmployeeColumns1RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllEmployeeColumns1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllEmployeeColumns1Response", Namespace="http://tempuri.org/", Order=0)]
        public HomepageApp.WebServiceClient.AllEmployeeColumns1ResponseBody Body;
        
        public AllEmployeeColumns1Response() {
        }
        
        public AllEmployeeColumns1Response(HomepageApp.WebServiceClient.AllEmployeeColumns1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllEmployeeColumns1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HomepageApp.WebServiceClient.ArrayOfString[] AllEmployeeColumns1Result;
        
        public AllEmployeeColumns1ResponseBody() {
        }
        
        public AllEmployeeColumns1ResponseBody(HomepageApp.WebServiceClient.ArrayOfString[] AllEmployeeColumns1Result) {
            this.AllEmployeeColumns1Result = AllEmployeeColumns1Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllEmployeeColumns2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllEmployeeColumns2", Namespace="http://tempuri.org/", Order=0)]
        public HomepageApp.WebServiceClient.AllEmployeeColumns2RequestBody Body;
        
        public AllEmployeeColumns2Request() {
        }
        
        public AllEmployeeColumns2Request(HomepageApp.WebServiceClient.AllEmployeeColumns2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AllEmployeeColumns2RequestBody {
        
        public AllEmployeeColumns2RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllEmployeeColumns2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllEmployeeColumns2Response", Namespace="http://tempuri.org/", Order=0)]
        public HomepageApp.WebServiceClient.AllEmployeeColumns2ResponseBody Body;
        
        public AllEmployeeColumns2Response() {
        }
        
        public AllEmployeeColumns2Response(HomepageApp.WebServiceClient.AllEmployeeColumns2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllEmployeeColumns2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HomepageApp.WebServiceClient.ArrayOfString[] AllEmployeeColumns2Result;
        
        public AllEmployeeColumns2ResponseBody() {
        }
        
        public AllEmployeeColumns2ResponseBody(HomepageApp.WebServiceClient.ArrayOfString[] AllEmployeeColumns2Result) {
            this.AllEmployeeColumns2Result = AllEmployeeColumns2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmployeeTablesTableNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmployeeTablesTableNames", Namespace="http://tempuri.org/", Order=0)]
        public HomepageApp.WebServiceClient.EmployeeTablesTableNamesRequestBody Body;
        
        public EmployeeTablesTableNamesRequest() {
        }
        
        public EmployeeTablesTableNamesRequest(HomepageApp.WebServiceClient.EmployeeTablesTableNamesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EmployeeTablesTableNamesRequestBody {
        
        public EmployeeTablesTableNamesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmployeeTablesTableNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmployeeTablesTableNamesResponse", Namespace="http://tempuri.org/", Order=0)]
        public HomepageApp.WebServiceClient.EmployeeTablesTableNamesResponseBody Body;
        
        public EmployeeTablesTableNamesResponse() {
        }
        
        public EmployeeTablesTableNamesResponse(HomepageApp.WebServiceClient.EmployeeTablesTableNamesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmployeeTablesTableNamesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HomepageApp.WebServiceClient.ArrayOfString EmployeeTablesTableNamesResult;
        
        public EmployeeTablesTableNamesResponseBody() {
        }
        
        public EmployeeTablesTableNamesResponseBody(HomepageApp.WebServiceClient.ArrayOfString EmployeeTablesTableNamesResult) {
            this.EmployeeTablesTableNamesResult = EmployeeTablesTableNamesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ERP2_WebServiceSoapChannel : HomepageApp.WebServiceClient.ERP2_WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ERP2_WebServiceSoapClient : System.ServiceModel.ClientBase<HomepageApp.WebServiceClient.ERP2_WebServiceSoap>, HomepageApp.WebServiceClient.ERP2_WebServiceSoap {
        
        public ERP2_WebServiceSoapClient() {
        }
        
        public ERP2_WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ERP2_WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ERP2_WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ERP2_WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HomepageApp.WebServiceClient.EmployeeContentsResponse HomepageApp.WebServiceClient.ERP2_WebServiceSoap.EmployeeContents(HomepageApp.WebServiceClient.EmployeeContentsRequest request) {
            return base.Channel.EmployeeContents(request);
        }
        
        public HomepageApp.WebServiceClient.ArrayOfString[] EmployeeContents(string args) {
            HomepageApp.WebServiceClient.EmployeeContentsRequest inValue = new HomepageApp.WebServiceClient.EmployeeContentsRequest();
            inValue.Body = new HomepageApp.WebServiceClient.EmployeeContentsRequestBody();
            inValue.Body.args = args;
            HomepageApp.WebServiceClient.EmployeeContentsResponse retVal = ((HomepageApp.WebServiceClient.ERP2_WebServiceSoap)(this)).EmployeeContents(inValue);
            return retVal.Body.EmployeeContentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HomepageApp.WebServiceClient.EmployeeContentsResponse> HomepageApp.WebServiceClient.ERP2_WebServiceSoap.EmployeeContentsAsync(HomepageApp.WebServiceClient.EmployeeContentsRequest request) {
            return base.Channel.EmployeeContentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HomepageApp.WebServiceClient.EmployeeContentsResponse> EmployeeContentsAsync(string args) {
            HomepageApp.WebServiceClient.EmployeeContentsRequest inValue = new HomepageApp.WebServiceClient.EmployeeContentsRequest();
            inValue.Body = new HomepageApp.WebServiceClient.EmployeeContentsRequestBody();
            inValue.Body.args = args;
            return ((HomepageApp.WebServiceClient.ERP2_WebServiceSoap)(this)).EmployeeContentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HomepageApp.WebServiceClient.EmployeeRelativesResponse HomepageApp.WebServiceClient.ERP2_WebServiceSoap.EmployeeRelatives(HomepageApp.WebServiceClient.EmployeeRelativesRequest request) {
            return base.Channel.EmployeeRelatives(request);
        }
        
        public HomepageApp.WebServiceClient.ArrayOfString[] EmployeeRelatives() {
            HomepageApp.WebServiceClient.EmployeeRelativesRequest inValue = new HomepageApp.WebServiceClient.EmployeeRelativesRequest();
            inValue.Body = new HomepageApp.WebServiceClient.EmployeeRelativesRequestBody();
            HomepageApp.WebServiceClient.EmployeeRelativesResponse retVal = ((HomepageApp.WebServiceClient.ERP2_WebServiceSoap)(this)).EmployeeRelatives(inValue);
            return retVal.Body.EmployeeRelativesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HomepageApp.WebServiceClient.EmployeeRelativesResponse> HomepageApp.WebServiceClient.ERP2_WebServiceSoap.EmployeeRelativesAsync(HomepageApp.WebServiceClient.EmployeeRelativesRequest request) {
            return base.Channel.EmployeeRelativesAsync(request);
        }
        
        public System.Threading.Tasks.Task<HomepageApp.WebServiceClient.EmployeeRelativesResponse> EmployeeRelativesAsync() {
            HomepageApp.WebServiceClient.EmployeeRelativesRequest inValue = new HomepageApp.WebServiceClient.EmployeeRelativesRequest();
            inValue.Body = new HomepageApp.WebServiceClient.EmployeeRelativesRequestBody();
            return ((HomepageApp.WebServiceClient.ERP2_WebServiceSoap)(this)).EmployeeRelativesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HomepageApp.WebServiceClient.SickEmployeesResponse HomepageApp.WebServiceClient.ERP2_WebServiceSoap.SickEmployees(HomepageApp.WebServiceClient.SickEmployeesRequest request) {
            return base.Channel.SickEmployees(request);
        }
        
        public HomepageApp.WebServiceClient.ArrayOfString[] SickEmployees() {
            HomepageApp.WebServiceClient.SickEmployeesRequest inValue = new HomepageApp.WebServiceClient.SickEmployeesRequest();
            inValue.Body = new HomepageApp.WebServiceClient.SickEmployeesRequestBody();
            HomepageApp.WebServiceClient.SickEmployeesResponse retVal = ((HomepageApp.WebServiceClient.ERP2_WebServiceSoap)(this)).SickEmployees(inValue);
            return retVal.Body.SickEmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HomepageApp.WebServiceClient.SickEmployeesResponse> HomepageApp.WebServiceClient.ERP2_WebServiceSoap.SickEmployeesAsync(HomepageApp.WebServiceClient.SickEmployeesRequest request) {
            return base.Channel.SickEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<HomepageApp.WebServiceClient.SickEmployeesResponse> SickEmployeesAsync() {
            HomepageApp.WebServiceClient.SickEmployeesRequest inValue = new HomepageApp.WebServiceClient.SickEmployeesRequest();
            inValue.Body = new HomepageApp.WebServiceClient.SickEmployeesRequestBody();
            return ((HomepageApp.WebServiceClient.ERP2_WebServiceSoap)(this)).SickEmployeesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HomepageApp.WebServiceClient.MostSickEmployeeResponse HomepageApp.WebServiceClient.ERP2_WebServiceSoap.MostSickEmployee(HomepageApp.WebServiceClient.MostSickEmployeeRequest request) {
            return base.Channel.MostSickEmployee(request);
        }
        
        public HomepageApp.WebServiceClient.ArrayOfString[] MostSickEmployee() {
            HomepageApp.WebServiceClient.MostSickEmployeeRequest inValue = new HomepageApp.WebServiceClient.MostSickEmployeeRequest();
            inValue.Body = new HomepageApp.WebServiceClient.MostSickEmployeeRequestBody();
            HomepageApp.WebServiceClient.MostSickEmployeeResponse retVal = ((HomepageApp.WebServiceClient.ERP2_WebServiceSoap)(this)).MostSickEmployee(inValue);
            return retVal.Body.MostSickEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HomepageApp.WebServiceClient.MostSickEmployeeResponse> HomepageApp.WebServiceClient.ERP2_WebServiceSoap.MostSickEmployeeAsync(HomepageApp.WebServiceClient.MostSickEmployeeRequest request) {
            return base.Channel.MostSickEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<HomepageApp.WebServiceClient.MostSickEmployeeResponse> MostSickEmployeeAsync() {
            HomepageApp.WebServiceClient.MostSickEmployeeRequest inValue = new HomepageApp.WebServiceClient.MostSickEmployeeRequest();
            inValue.Body = new HomepageApp.WebServiceClient.MostSickEmployeeRequestBody();
            return ((HomepageApp.WebServiceClient.ERP2_WebServiceSoap)(this)).MostSickEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HomepageApp.WebServiceClient.GetAllKeysResponse HomepageApp.WebServiceClient.ERP2_WebServiceSoap.GetAllKeys(HomepageApp.WebServiceClient.GetAllKeysRequest request) {
            return base.Channel.GetAllKeys(request);
        }
        
        public HomepageApp.WebServiceClient.ArrayOfString[] GetAllKeys(string args) {
            HomepageApp.WebServiceClient.GetAllKeysRequest inValue = new HomepageApp.WebServiceClient.GetAllKeysRequest();
            inValue.Body = new HomepageApp.WebServiceClient.GetAllKeysRequestBody();
            inValue.Body.args = args;
            HomepageApp.WebServiceClient.GetAllKeysResponse retVal = ((HomepageApp.WebServiceClient.ERP2_WebServiceSoap)(this)).GetAllKeys(inValue);
            return retVal.Body.GetAllKeysResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HomepageApp.WebServiceClient.GetAllKeysResponse> HomepageApp.WebServiceClient.ERP2_WebServiceSoap.GetAllKeysAsync(HomepageApp.WebServiceClient.GetAllKeysRequest request) {
            return base.Channel.GetAllKeysAsync(request);
        }
        
        public System.Threading.Tasks.Task<HomepageApp.WebServiceClient.GetAllKeysResponse> GetAllKeysAsync(string args) {
            HomepageApp.WebServiceClient.GetAllKeysRequest inValue = new HomepageApp.WebServiceClient.GetAllKeysRequest();
            inValue.Body = new HomepageApp.WebServiceClient.GetAllKeysRequestBody();
            inValue.Body.args = args;
            return ((HomepageApp.WebServiceClient.ERP2_WebServiceSoap)(this)).GetAllKeysAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HomepageApp.WebServiceClient.AllIndexesResponse HomepageApp.WebServiceClient.ERP2_WebServiceSoap.AllIndexes(HomepageApp.WebServiceClient.AllIndexesRequest request) {
            return base.Channel.AllIndexes(request);
        }
        
        public HomepageApp.WebServiceClient.ArrayOfString[] AllIndexes(string args) {
            HomepageApp.WebServiceClient.AllIndexesRequest inValue = new HomepageApp.WebServiceClient.AllIndexesRequest();
            inValue.Body = new HomepageApp.WebServiceClient.AllIndexesRequestBody();
            inValue.Body.args = args;
            HomepageApp.WebServiceClient.AllIndexesResponse retVal = ((HomepageApp.WebServiceClient.ERP2_WebServiceSoap)(this)).AllIndexes(inValue);
            return retVal.Body.AllIndexesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HomepageApp.WebServiceClient.AllIndexesResponse> HomepageApp.WebServiceClient.ERP2_WebServiceSoap.AllIndexesAsync(HomepageApp.WebServiceClient.AllIndexesRequest request) {
            return base.Channel.AllIndexesAsync(request);
        }
        
        public System.Threading.Tasks.Task<HomepageApp.WebServiceClient.AllIndexesResponse> AllIndexesAsync(string args) {
            HomepageApp.WebServiceClient.AllIndexesRequest inValue = new HomepageApp.WebServiceClient.AllIndexesRequest();
            inValue.Body = new HomepageApp.WebServiceClient.AllIndexesRequestBody();
            inValue.Body.args = args;
            return ((HomepageApp.WebServiceClient.ERP2_WebServiceSoap)(this)).AllIndexesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HomepageApp.WebServiceClient.AllConstraintsResponse HomepageApp.WebServiceClient.ERP2_WebServiceSoap.AllConstraints(HomepageApp.WebServiceClient.AllConstraintsRequest request) {
            return base.Channel.AllConstraints(request);
        }
        
        public HomepageApp.WebServiceClient.ArrayOfString[] AllConstraints(string args) {
            HomepageApp.WebServiceClient.AllConstraintsRequest inValue = new HomepageApp.WebServiceClient.AllConstraintsRequest();
            inValue.Body = new HomepageApp.WebServiceClient.AllConstraintsRequestBody();
            inValue.Body.args = args;
            HomepageApp.WebServiceClient.AllConstraintsResponse retVal = ((HomepageApp.WebServiceClient.ERP2_WebServiceSoap)(this)).AllConstraints(inValue);
            return retVal.Body.AllConstraintsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HomepageApp.WebServiceClient.AllConstraintsResponse> HomepageApp.WebServiceClient.ERP2_WebServiceSoap.AllConstraintsAsync(HomepageApp.WebServiceClient.AllConstraintsRequest request) {
            return base.Channel.AllConstraintsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HomepageApp.WebServiceClient.AllConstraintsResponse> AllConstraintsAsync(string args) {
            HomepageApp.WebServiceClient.AllConstraintsRequest inValue = new HomepageApp.WebServiceClient.AllConstraintsRequest();
            inValue.Body = new HomepageApp.WebServiceClient.AllConstraintsRequestBody();
            inValue.Body.args = args;
            return ((HomepageApp.WebServiceClient.ERP2_WebServiceSoap)(this)).AllConstraintsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HomepageApp.WebServiceClient.AllTableNames1Response HomepageApp.WebServiceClient.ERP2_WebServiceSoap.AllTableNames1(HomepageApp.WebServiceClient.AllTableNames1Request request) {
            return base.Channel.AllTableNames1(request);
        }
        
        public HomepageApp.WebServiceClient.ArrayOfString[] AllTableNames1() {
            HomepageApp.WebServiceClient.AllTableNames1Request inValue = new HomepageApp.WebServiceClient.AllTableNames1Request();
            inValue.Body = new HomepageApp.WebServiceClient.AllTableNames1RequestBody();
            HomepageApp.WebServiceClient.AllTableNames1Response retVal = ((HomepageApp.WebServiceClient.ERP2_WebServiceSoap)(this)).AllTableNames1(inValue);
            return retVal.Body.AllTableNames1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HomepageApp.WebServiceClient.AllTableNames1Response> HomepageApp.WebServiceClient.ERP2_WebServiceSoap.AllTableNames1Async(HomepageApp.WebServiceClient.AllTableNames1Request request) {
            return base.Channel.AllTableNames1Async(request);
        }
        
        public System.Threading.Tasks.Task<HomepageApp.WebServiceClient.AllTableNames1Response> AllTableNames1Async() {
            HomepageApp.WebServiceClient.AllTableNames1Request inValue = new HomepageApp.WebServiceClient.AllTableNames1Request();
            inValue.Body = new HomepageApp.WebServiceClient.AllTableNames1RequestBody();
            return ((HomepageApp.WebServiceClient.ERP2_WebServiceSoap)(this)).AllTableNames1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HomepageApp.WebServiceClient.AllTableNames2Response HomepageApp.WebServiceClient.ERP2_WebServiceSoap.AllTableNames2(HomepageApp.WebServiceClient.AllTableNames2Request request) {
            return base.Channel.AllTableNames2(request);
        }
        
        public HomepageApp.WebServiceClient.ArrayOfString[] AllTableNames2() {
            HomepageApp.WebServiceClient.AllTableNames2Request inValue = new HomepageApp.WebServiceClient.AllTableNames2Request();
            inValue.Body = new HomepageApp.WebServiceClient.AllTableNames2RequestBody();
            HomepageApp.WebServiceClient.AllTableNames2Response retVal = ((HomepageApp.WebServiceClient.ERP2_WebServiceSoap)(this)).AllTableNames2(inValue);
            return retVal.Body.AllTableNames2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HomepageApp.WebServiceClient.AllTableNames2Response> HomepageApp.WebServiceClient.ERP2_WebServiceSoap.AllTableNames2Async(HomepageApp.WebServiceClient.AllTableNames2Request request) {
            return base.Channel.AllTableNames2Async(request);
        }
        
        public System.Threading.Tasks.Task<HomepageApp.WebServiceClient.AllTableNames2Response> AllTableNames2Async() {
            HomepageApp.WebServiceClient.AllTableNames2Request inValue = new HomepageApp.WebServiceClient.AllTableNames2Request();
            inValue.Body = new HomepageApp.WebServiceClient.AllTableNames2RequestBody();
            return ((HomepageApp.WebServiceClient.ERP2_WebServiceSoap)(this)).AllTableNames2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HomepageApp.WebServiceClient.AllEmployeeColumns1Response HomepageApp.WebServiceClient.ERP2_WebServiceSoap.AllEmployeeColumns1(HomepageApp.WebServiceClient.AllEmployeeColumns1Request request) {
            return base.Channel.AllEmployeeColumns1(request);
        }
        
        public HomepageApp.WebServiceClient.ArrayOfString[] AllEmployeeColumns1() {
            HomepageApp.WebServiceClient.AllEmployeeColumns1Request inValue = new HomepageApp.WebServiceClient.AllEmployeeColumns1Request();
            inValue.Body = new HomepageApp.WebServiceClient.AllEmployeeColumns1RequestBody();
            HomepageApp.WebServiceClient.AllEmployeeColumns1Response retVal = ((HomepageApp.WebServiceClient.ERP2_WebServiceSoap)(this)).AllEmployeeColumns1(inValue);
            return retVal.Body.AllEmployeeColumns1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HomepageApp.WebServiceClient.AllEmployeeColumns1Response> HomepageApp.WebServiceClient.ERP2_WebServiceSoap.AllEmployeeColumns1Async(HomepageApp.WebServiceClient.AllEmployeeColumns1Request request) {
            return base.Channel.AllEmployeeColumns1Async(request);
        }
        
        public System.Threading.Tasks.Task<HomepageApp.WebServiceClient.AllEmployeeColumns1Response> AllEmployeeColumns1Async() {
            HomepageApp.WebServiceClient.AllEmployeeColumns1Request inValue = new HomepageApp.WebServiceClient.AllEmployeeColumns1Request();
            inValue.Body = new HomepageApp.WebServiceClient.AllEmployeeColumns1RequestBody();
            return ((HomepageApp.WebServiceClient.ERP2_WebServiceSoap)(this)).AllEmployeeColumns1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HomepageApp.WebServiceClient.AllEmployeeColumns2Response HomepageApp.WebServiceClient.ERP2_WebServiceSoap.AllEmployeeColumns2(HomepageApp.WebServiceClient.AllEmployeeColumns2Request request) {
            return base.Channel.AllEmployeeColumns2(request);
        }
        
        public HomepageApp.WebServiceClient.ArrayOfString[] AllEmployeeColumns2() {
            HomepageApp.WebServiceClient.AllEmployeeColumns2Request inValue = new HomepageApp.WebServiceClient.AllEmployeeColumns2Request();
            inValue.Body = new HomepageApp.WebServiceClient.AllEmployeeColumns2RequestBody();
            HomepageApp.WebServiceClient.AllEmployeeColumns2Response retVal = ((HomepageApp.WebServiceClient.ERP2_WebServiceSoap)(this)).AllEmployeeColumns2(inValue);
            return retVal.Body.AllEmployeeColumns2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HomepageApp.WebServiceClient.AllEmployeeColumns2Response> HomepageApp.WebServiceClient.ERP2_WebServiceSoap.AllEmployeeColumns2Async(HomepageApp.WebServiceClient.AllEmployeeColumns2Request request) {
            return base.Channel.AllEmployeeColumns2Async(request);
        }
        
        public System.Threading.Tasks.Task<HomepageApp.WebServiceClient.AllEmployeeColumns2Response> AllEmployeeColumns2Async() {
            HomepageApp.WebServiceClient.AllEmployeeColumns2Request inValue = new HomepageApp.WebServiceClient.AllEmployeeColumns2Request();
            inValue.Body = new HomepageApp.WebServiceClient.AllEmployeeColumns2RequestBody();
            return ((HomepageApp.WebServiceClient.ERP2_WebServiceSoap)(this)).AllEmployeeColumns2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HomepageApp.WebServiceClient.EmployeeTablesTableNamesResponse HomepageApp.WebServiceClient.ERP2_WebServiceSoap.EmployeeTablesTableNames(HomepageApp.WebServiceClient.EmployeeTablesTableNamesRequest request) {
            return base.Channel.EmployeeTablesTableNames(request);
        }
        
        public HomepageApp.WebServiceClient.ArrayOfString EmployeeTablesTableNames() {
            HomepageApp.WebServiceClient.EmployeeTablesTableNamesRequest inValue = new HomepageApp.WebServiceClient.EmployeeTablesTableNamesRequest();
            inValue.Body = new HomepageApp.WebServiceClient.EmployeeTablesTableNamesRequestBody();
            HomepageApp.WebServiceClient.EmployeeTablesTableNamesResponse retVal = ((HomepageApp.WebServiceClient.ERP2_WebServiceSoap)(this)).EmployeeTablesTableNames(inValue);
            return retVal.Body.EmployeeTablesTableNamesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HomepageApp.WebServiceClient.EmployeeTablesTableNamesResponse> HomepageApp.WebServiceClient.ERP2_WebServiceSoap.EmployeeTablesTableNamesAsync(HomepageApp.WebServiceClient.EmployeeTablesTableNamesRequest request) {
            return base.Channel.EmployeeTablesTableNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<HomepageApp.WebServiceClient.EmployeeTablesTableNamesResponse> EmployeeTablesTableNamesAsync() {
            HomepageApp.WebServiceClient.EmployeeTablesTableNamesRequest inValue = new HomepageApp.WebServiceClient.EmployeeTablesTableNamesRequest();
            inValue.Body = new HomepageApp.WebServiceClient.EmployeeTablesTableNamesRequestBody();
            return ((HomepageApp.WebServiceClient.ERP2_WebServiceSoap)(this)).EmployeeTablesTableNamesAsync(inValue);
        }
    }
}
